# Generated by Django 5.0.7 on 2024-10-21 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgid', models.CharField(max_length=100, unique=True)),
                ('orgname', models.CharField(max_length=200)),
                ('orgemail', models.EmailField(max_length=254, unique=True)),
                ('orgpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.CharField(max_length=100, unique=True)),
                ('studname', models.CharField(max_length=200)),
                ('studprogramme', models.CharField(max_length=100)),
                ('studpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
    ]
